apiVersion: batch/v1
kind: Job
metadata:
  generateName: awave-a100-
  labels:
    eidf/user: s2824305-epcc
    kueue.x-k8s.io/max-exec-time-seconds: "300"
    kueue.x-k8s.io/queue-name: eidf018ns-profiling-queue

spec:
  completions: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 180
  template:
    metadata:
      labels:
        eidf/user: s2824305-epcc

    spec:
      activeDeadlineSeconds: 300
      containers:
      - name: run
        image: $container
        command:
          - bash
          - -c
          - >-
            cd ${KGPU_SUBMIT_DIR} &&
            mpirun -n 1 -mca coll ^hcoll ./build-CUDA/awave
            -mpi 1,1,1 -shape 128,128,128 -nsteps 100 -out_period 100
            ${KGPU_JOB_NAME} > ${KGPU_JOB_NAME}.log 2>&1
        resources:
          requests:
            cpu: 1
            memory: 32Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 8
            memory: 32Gi
            nvidia.com/gpu: 1
      restartPolicy: Never
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-A100-SXM4-80GB
