apiVersion: batch/v1
kind: Job
metadata:
  generateName: awave-h100-n1024-g8-
spec:
  completions: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 1800
  template:
    metadata:
      name: awave-h100-pod
      labels:
        kueue.x-k8s.io/max-exec-time-seconds: "7200"
        kueue.x-k8s.io/queue-name: eidf018ns-profiling-queue
    spec:
      activeDeadlineSeconds: 7200
      restartPolicy: Never
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 32Gi
      containers:
        - name: run
          image: $container
          resources:
            requests:
              cpu: 16
              memory: 180Gi
              nvidia.com/gpu: 8
            limits:
              cpu: 16
              memory: 180Gi
              nvidia.com/gpu: 8
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          command: ["bash", "-c"]
          args:
            - |-
              set -euo pipefail
              cd ${KGPU_SUBMIT_DIR}
              mkdir -p results/h100/g8
              mpirun -n 8 -mca coll ^hcoll ./build-CUDA/awave -mpi 2,2,2 -shape 1024,1024,1024 -nsteps 100 -out_period 100 -skip_cpu 1 -json results/h100/g8/n1024_g8.json ${KGPU_JOB_NAME} 2>&1 | tee results/h100/g8/n1024_g8.log
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3
