apiVersion: batch/v1
kind: Job
metadata:
  generateName: awave-h100-n512-g1-
spec:
  completions: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 1800
  template:
    metadata:
      name: awave-h100-pod
      labels:
        kueue.x-k8s.io/max-exec-time-seconds: "7200"
        kueue.x-k8s.io/queue-name: eidf018ns-profiling-queue
    spec:
      activeDeadlineSeconds: 7200
      restartPolicy: Never
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 32Gi
      containers:
        - name: run
          image: $container
          resources:
            requests:
              cpu: 4
              memory: 32Gi
              nvidia.com/gpu: 1
            limits:
              cpu: 8
              memory: 32Gi
              nvidia.com/gpu: 1
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          command: ["bash", "-c"]
          args:
            - |-
              set -euo pipefail
              cd ${KGPU_SUBMIT_DIR}
              mkdir -p results/h100/g1
              mpirun -n 1 -mca coll ^hcoll ./build-CUDA/awave -mpi 1,1,1 -shape 512,512,512 -nsteps 100 -out_period 100 -skip_cpu 1 -json results/h100/g1/n512_g1.json ${KGPU_JOB_NAME} 2>&1 | tee results/h100/g1/n512_g1.log
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3
